### ISSUE TITLE
build fail because this line.

### ISSUE THREAD

**Issue by smuel1414** [AviMarineInnovatons/BoatAngels#81]
https://github.com/AviMarineInnovatons/BoatAngels/blob/529da461c1351e0e5e2301ec48b6e94a5fa13287/app/src/main/java/in/avimarine/boatangels/geographical/WeatherHttpClient.java#L31

build fail because 
D:\a\1\s\app\src\main\java\in\avimarine\boatangels\geographical\
WeatherHttpClient.java:31: error: cannot find symbol
API_KEY = "&APPID="+c.getString(R.string.OPENWEATHERMAPAPPID); 00000000000000000000000000000000000

is it failing on local builds?

**Comment by smuel1414** [comment]
[7.txt](https://github.com/AviMarineInnovatons/BoatAngels/files/2265822/7.txt)

**Comment by aayaffe** [comment]
There is a manual in the wiki about how to fix this issue
