### ISSUE TITLE
firebase function Push Notification trigger by firestore cloud

### ISSUE THREAD

**Issue by motim6026** [AviMarineInnovatons/BoatAngels#87]
* when user inspect boat the function cloud send push notification to boat owner.

**Comment by aayaffe** [comment]
Duplicate of #33

**Comment by motim6026** [comment]
נכון אני אמחק את המשימה הישנה תכף.
בגדול המשימה החדשה זה להגיע ליכולת של notification שמנוהל ב-firebase
function.
במשימה הישנה ה-notifi נשלח device to device  מה שלא נותן לנו יכולת ניהול
ומעמיס על הclient .
